### PR TITLE
Add WORKDIR

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: svor <vsvydenk@redhat.com>
Adds WORKDIR into the Dockerfile to fix the problem with running netcoredbg.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by svor** [comment]
@benoitf Could you pls merge it, I don't have permissions.

**Comment by benoitf** [comment]
@svor I sent you a message this morning on slack saying that you should have received a github invitation

**Comment by benoitf** [comment]
```
Invitations are sent via email and can be accepted at https://github.com/che-dockerfiles
```

**Comment by svor** [comment]
Got it, thanks!

**Pull request merged**
